const PROJECTS = [

  /* ─── JUPITER ─── */
  {
    id: 'onboarding-redesign',
    title: 'Onboarding Redesign',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'ux-writing',
    disciplineLabel: 'UX Writing',
    metric: '−34% drop-off',
    dek: 'How rewriting Jupiter\'s first-run experience reduced drop-off by 34%.',
    body: 'The brief was simple: stop losing users before they even started. The problem turned out to be the words — jargon where there should have been warmth, instructions where there should have been direction. Rewrote 18 screens. Watched the numbers move.',
    process: 'Mapped every screen to a user emotion before touching a single word.',
    tags: ['Content Design', 'A/B Testing', '2024'],
    url: 'case-study.html?id=onboarding-redesign',
    hero: true,      // ← homepage big card
    featured: false, // ← homepage grid
    live: true,
  },
  {
    id: 'error-message-audit',
    title: 'Error Message Audit',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'ux-writing',
    disciplineLabel: 'UX Writing',
    metric: '200+ rewrites',
    dek: 'Audited and rewrote 200+ error messages. "Something went wrong" wasn\'t helping anyone.',
    body: 'Started with the worst offenders — errors that blamed users instead of helping them. Established a pattern. Rewrote the rest in batches.',
    process: 'Started with the worst offenders — errors that blamed users. Rewrote those first, established the pattern.',
    tags: ['Error States', 'Audit', '2024'],
    url: 'case-study.html?id=error-message-audit',
    hero: false,
    featured: true,
    live: true,
  },
  {
    id: 'investments-flow',
    title: 'Investments Flow',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'ux-writing',
    disciplineLabel: 'UX Writing',
    metric: 'Add metric',
    dek: 'Led content design for Jupiter\'s Investments product — from discovery to portfolio management.',
    body: 'Complex financial concepts, plain language. Every screen had to earn its place.',
    process: 'Ran a jargon audit first — listed every term users had to understand. Then systematically replaced or explained each one.',
    tags: ['Fintech', 'Content Design', '2024'],
    url: 'case-study.html?id=investments-flow',
    hero: false,
    featured: false,
    live: true,
  },
  {
    id: 'jupiter-voice-guide',
    title: 'Jupiter Voice Guide',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'tone-of-voice',
    disciplineLabel: 'Tone of Voice',
    metric: 'Add metric',
    dek: 'Built Jupiter\'s voice and tone framework — making sure every surface sounds like one person wrote it.',
    body: 'From tooltips to push notifications. One voice, many surfaces, zero exceptions.',
    process: 'Audited live copy first — catalogued every inconsistency before writing a single rule.',
    tags: ['Voice & Tone', 'Brand', '2024'],
    url: 'case-study.html?id=jupiter-voice-guide',
    hero: false,
    featured: false,
    live: true,
  },
  {
    id: 'jupiter-product-brand',
    title: 'New Product Brand',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'branding',
    disciplineLabel: 'Branding',
    metric: '0 → Launch',
    dek: 'Owned branding end-to-end for a new Jupiter product — naming, positioning, voice, visual language.',
    body: 'Built from zero to launch-ready. Naming, positioning, voice direction, and the full creative brief.',
    process: 'Started with positioning — only then moved to naming. A name without a position is just a label.',
    tags: ['Naming', 'Positioning', '2024'],
    url: 'case-study.html?id=jupiter-product-brand',
    hero: false,
    featured: false,
    live: true,
  },
  {
    id: 'savings-campaign',
    title: 'Savings Account Campaign',
    company: 'jupiter',
    companyLabel: 'Jupiter',
    discipline: 'product-marketing',
    disciplineLabel: 'Product Marketing',
    metric: 'Add metric',
    dek: 'Growth campaign for Jupiter\'s Savings Account — from in-app prompts to external creative.',
    body: 'One message, many surfaces, one metric to move. The challenge was consistency without repetition.',
    process: 'Mapped every surface before writing a word — otherwise you end up with seven slightly different messages.',
    tags: ['Growth', 'Campaign', '2024'],
    url: 'case-study.html?id=savings-campaign',
    hero: false,
    featured: false,
    live: true,
  },

  /* ─── LEAP SCHOLAR ─── */
  {
    id: 'leap-product-copy',
    title: 'End-to-End Product Copy',
    company: 'leap',
    companyLabel: 'Leap Scholar',
    discipline: 'ux-writing',
    disciplineLabel: 'UX Writing',
    metric: 'Entire product suite',
    dek: 'Managed all UX copy across Leap\'s product suite as a one-person writing team.',
    body: 'From onboarding to error states — every word in the product was mine to get right. No brief too small, no surface too obscure.',
    process: 'No brief is complete until you\'ve mapped the emotional state of the user at each step. Started there every time.',
    tags: ['Full Product', 'EdTech', '2022–2024'],
    url: 'case-study.html?id=leap-product-copy',
    hero: false,
    featured: true,
    live: true,
  },
  {
    id: 'leap-voice-tone',
    title: 'Voice & Tone Framework',
    company: 'leap',
    companyLabel: 'Leap Scholar',
    discipline: 'tone-of-voice',
    disciplineLabel: 'Tone of Voice',
    metric: 'Whole org aligned',
    dek: 'Built a voice framework from scratch. Gave everyone the tools to sound human without sounding identical.',
    body: 'Ran workshops with writers before writing a single rule — principles had to come from the team, not at them.',
    process: 'Ran workshops before writing a single rule — principles had to come from the team, not at them.',
    tags: ['Voice & Tone', 'Strategy', '2023'],
    url: 'case-study.html?id=leap-voice-tone',
    hero: false,
    featured: true,
    live: true,
  },
  {
    id: 'leap-campaigns',
    title: 'Feature Adoption Campaigns',
    company: 'leap',
    companyLabel: 'Leap Scholar',
    discipline: 'product-marketing',
    disciplineLabel: 'Product Marketing',
    metric: 'Add metric',
    dek: 'Ran growth campaigns for boosting feature adoption, engagement, retention, and referrals.',
    body: 'Across multiple products and user segments. Each campaign started with one question: what does this user actually want to do?',
    process: 'Each campaign started with the user\'s goal, not the product\'s goal. Usually different things.',
    tags: ['Growth', 'Retention', '2022–2024'],
    url: 'case-study.html?id=leap-campaigns',
    hero: false,
    featured: false,
    live: true,
  },

  /* ─── VAHAK ─── */
  {
    id: 'vahak-seo',
    title: 'Organic Traffic Overhaul',
    company: 'vahak',
    companyLabel: 'Vahak',
    discipline: 'seo',
    disciplineLabel: 'SEO',
    metric: '4× traffic growth',
    dek: 'Took Vahak\'s monthly organic traffic from ~2,500 to ~10,000 in 3 months.',
    body: 'Content strategy, keyword architecture, and writing — all of it. Started with what was already ranking, then figured out why. Built from signal, not assumption.',
    process: 'Started with what was already ranking, then figured out why. Built from signal, not assumption.',
    tags: ['SEO', 'Content Strategy', '2021'],
    url: 'case-study.html?id=vahak-seo',
    hero: false,
    featured: false,
    live: true,
  },
  {
    id: 'vahak-comms',
    title: 'Transactional Comms',
    company: 'vahak',
    companyLabel: 'Vahak',
    discipline: 'ux-writing',
    disciplineLabel: 'UX Writing',
    metric: 'Add metric',
    dek: 'Managed journeys for transactional and promotional comms — push, SMS, email.',
    body: 'Copy that had to work first time, every time. No room for ambiguity when someone\'s tracking a truck.',
    process: 'Wrote for the worst case first — what if the user has no context? If it works then, it works always.',
    tags: ['Push', 'Transactional', '2021–2022'],
    url: 'case-study.html?id=vahak-comms',
    hero: false,
    featured: false,
    live: true,
  },
];
